version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:4
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    build: .
    image: polls-api
    restart: always
    command: npm start
    volumes:
      - ./dist:/usr/src/polls-api/dist
    ports:
      - "3333:3333"
    links:
      - mongo
