version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:4
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"
  api:
    container_name: api-container
    build: .
    image: polls-api
    restart: always
    command: npm run start
    volumes:
      - ./dist:/usr/src/polls-api/dist
      - ./package.json/usr/src/polls-api/package.json
    ports:
      - "3333:3333"
      - "9222:9222"
    links:
      - mongo
