version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:4
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"
  api:
    container_name: api-container
    image: node:14
    working_dir: /usr/src/polls-api
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    volumes:
      - ./dist:/usr/src/polls-api/dist
      - ./package.json:/usr/src/polls-api/package.json
    ports:
      - "3333:3333"
      - "9222:9222"
    links:
      - mongo
